# This is a basic workflow to help you get started with Actions

name:  Auto message for PR's and Issues

# Controls when the workflow will run
on: [pull_request, issues]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: PR and Issue Meassage
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hey, thank you for opening this Issue ! 🙂"
          pr-message: "Thank You For opening Pull_Request. <br>In order to merge it in main branch one approved Review must be required"
